version: 2

models:
  - name: fct_messages
    description: "One row per telegram message"
    columns:
      - name: message_id
        tests:
          - unique
          - not_null
      - name: channel_key
        tests:
          - relationships:
              to: ref('dim_channels')
              field: channel_key

  - name: dim_channels
    columns:
      - name: channel_key
        tests:
          - unique
          - not_null